services:
  backend:
    build: ../backend
    restart: unless-stopped
    ports:
      - ${DEBUG_PORT}:${DEBUG_PORT}
      - ${BACKEND_PUBLISHED_PORT}:${BACKEND_TARGET_PORT}
    volumes:
      - ../backend:/app
    environment:
      ENV: ${ENV}
      HOST: ${BACKEND_HOST}
      PORT: ${BACKEND_PUBLISHED_PORT}
      USE_DEBUG: ${DEBUG}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      DEBUG_PORT: ${DEBUG_PORT}  
    entrypoint: [ "sh", "./entrypoint.sh" ]
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${BACKEND_PUBLISHED_PORT}/v1/healthcheck"
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PUBLISHED_PORT}:3306"
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db-volume:
    driver: local
